name: ceylon_therapist 
description: "Your Ayurvedic Practice, Streamlined."
publish_to: "none"

version: 1.1.6+16

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10
  audioplayers: ^5.0.0
  table_calendar: ^3.0.9
  http: ^1.1.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  # connectivity_plus: ^4.0.2
  # internet_connection_checker: ^1.0.0+1
  url_launcher: ^6.2.2  # Add this for launching maps

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1  # Moved here from dependencies

# This configuration block should be at ROOT level, not under flutter:
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"  # Create a proper app icon
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/icon/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/splash.png
    - assets/icon/app_icon.png